'use strict';
const fs = require('node:fs'); const vm = require('node:vm'); const { webcrypto } = require('node:crypto');
function assert(condition, message) { if (!condition) throw new Error(message); }
function expectThrow(fn, message) { let threw = false; try { fn(); } catch (_error) { threw = true; } assert(threw, message); }
global.window = global; if (!global.crypto) global.crypto = webcrypto; if (!global.Blob) global.Blob = require('node:buffer').Blob;
const memoryStore = new Map(); global.localStorage = { getItem(key) { return memoryStore.has(key) ? memoryStore.get(key) : null; }, setItem(key, value) { memoryStore.set(key, String(value)); }, removeItem(key) { memoryStore.delete(key); } };
for (const file of ['assets/js/market-engine.js', 'assets/js/storage.js']) vm.runInThisContext(fs.readFileSync(file, 'utf8'), { filename: file });
const engine = global.StockSandbox.Engine; const storage = global.StockSandbox.Storage; assert(engine && storage, 'engine and storage must load'); assert(engine.SCHEMA_VERSION === 2, 'schema version must be 2'); assert(engine.MAX_COMPANIES === 1, 'only one company is supported');
const state = engine.createDefaultState(123456789); assert(state.day === 60, 'default state should start at day 60'); assert(state.companies.length === 1, 'default state should have one company'); assert(state.companies[0].name === 'テスト企業', 'initial company name should be テスト企業'); assert(state.companies[0].candles.length === 60, 'default chart should have 60 candles');
const company = engine.currentCompany(state); engine.setCurrentPrice(state, 1234.56); assert(Math.abs(company.price - 1234.56) < 1e-9, 'direct price edit must update company price'); assert(company.candles[company.candles.length - 1].close === company.price, 'direct price edit must update latest close'); const beforeQuick = company.price; engine.adjustCurrentPrice(state, 10); assert(company.price > beforeQuick, 'quick positive price move should raise price');
engine.updateCompany(state, { name: '自由な名前', marketCap: 54321, per: -25, volatility: 77, drift: -12 }); assert(company.name === '自由な名前', 'company name should be freely editable'); assert(company.marketCap === 54321, 'market cap should update immediately'); assert(company.per === -25, 'PER should allow negative values'); assert(company.volatility === 77, 'volatility should update'); assert(company.drift === -12, 'drift should update');
const initialDay = state.day; engine.stepMarket(state, 5); assert(state.day === initialDay + 5, 'market stepping should advance time'); assert(company.candles[company.candles.length - 1].day === state.day, 'latest candle must match current day'); assert(company.candles.every((candle) => [candle.open, candle.high, candle.low, candle.close].every(Number.isFinite)), 'candles must stay finite');
const beforeCash = state.cash; let result = engine.executeTrade(state, 'buy', 1); assert(result.ok, 'basic buy should succeed'); assert(state.cash < beforeCash, 'buy should reduce cash'); result = engine.executeTrade(state, 'sell', 1); assert(result.ok, 'basic sell should succeed'); assert(state.positions[engine.COMPANY_ID].quantity === 0, 'round trip should close position'); result = engine.executeTrade(state, 'sell', 1); assert(!result.ok, 'short sale should be blocked by default'); state.allowShort = true; result = engine.executeTrade(state, 'sell', 1); assert(result.ok, 'short sale should work when enabled'); result = engine.executeTrade(state, 'buy', 1); assert(result.ok && state.positions[engine.COMPANY_ID].quantity === 0, 'buy should close short position');
state.positions[engine.COMPANY_ID] = { quantity: engine.MAX_POSITION, averagePrice: company.price }; result = engine.executeTrade(state, 'buy', 1); assert(!result.ok, 'position safety limit must be enforced'); state.positions[engine.COMPANY_ID] = { quantity: 0, averagePrice: 0 };
for (let index = 0; index < 7; index += 1) engine.stepMarket(state, 200); assert(company.candles.length <= engine.MAX_CANDLES, 'runtime candle cap must be enforced');
const saveResult = storage.saveState(state); assert(saveResult.ok, 'valid state should save'); assert(memoryStore.has(storage.STORAGE_KEY), 'v2 storage key should be used'); const raw = memoryStore.get(storage.STORAGE_KEY); assert(Buffer.byteLength(raw, 'utf8') <= storage.MAX_LOCAL_SAVE_BYTES, 'local save must respect byte budget'); const loaded = storage.loadState(); assert(loaded.ok && !loaded.migrated, 'v2 state should load without migration'); assert(loaded.state.companies.length === 1, 'loaded state should still have one company');
const invalidMultiple = JSON.parse(JSON.stringify(loaded.state)); invalidMultiple.companies.push(JSON.parse(JSON.stringify(invalidMultiple.companies[0]))); expectThrow(() => storage.validateState(invalidMultiple), 'multiple companies must be rejected in v2');
memoryStore.delete(storage.STORAGE_KEY); const legacyCompany = JSON.parse(JSON.stringify(loaded.state.companies[0])); legacyCompany.id = 'old-company'; const legacy = { ...JSON.parse(JSON.stringify(loaded.state)), schemaVersion: 1, selectedCompanyId: 'old-company', companies: [legacyCompany], positions: { 'old-company': { quantity: 3, averagePrice: legacyCompany.price } }, trades: [] }; memoryStore.set(storage.LEGACY_STORAGE_KEY, JSON.stringify(legacy)); const migrated = storage.loadState(); assert(migrated.ok && migrated.migrated, 'legacy v1 state should migrate'); assert(migrated.state.companies.length === 1, 'legacy migration should keep one company'); assert(migrated.state.companies[0].id === engine.COMPANY_ID, 'legacy company id should normalize'); assert(migrated.state.positions[engine.COMPANY_ID].quantity === 3, 'legacy selected position should migrate');
const controlledName = engine.normalizeCompanyInput({ name: '安全\u202e表示\n会社', price: 100 }); assert(!/[\u0000-\u001f\u007f-\u009f\u202a-\u202e\u2066-\u2069]/.test(controlledName.name), 'invisible control characters must be removed'); console.log('OK: smoke tests passed');
